import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

if (!supabaseUrl || !supabaseKey) {
  throw new Error('Missing Supabase environment variables')
}

export const supabase = createClient(supabaseUrl, supabaseKey)

export interface User {
  id: string // UUID generated by database
  privy_id: string | null // Privy DID
  email: string
  user_type: 'user' | 'organization'
  created_at: string
  updated_at: string
}

export interface UserProfile {
  id: string
  name: string
  age?: number | null
  location?: string | null
  profile_pic_url?: string | null
  phone?: string | null
  bio?: string | null
  wallet_address?: string | null
  created_at: string
  updated_at: string
}

export interface OrganizationProfile {
  id: string
  name: string
  location?: string | null
  profile_pic_url?: string | null
  registration_number?: string | null
  website_url?: string | null
  phone?: string | null
  description?: string | null
  established_date?: string | null
  wallet_address?: string | null
  created_at: string
  updated_at: string
}
